Repository josoavj/TPAlgoML_140225, pull requests merged in 2025-02, with the labels that each got.

#1 Create README.md
  README.md
Labels: documentation

#2 Update README.md
  README.md
Labels: documentation

#3 Create fanorona.py
  fanorona.py
Labels: bug, enhancement

#4 Update README.md
  README.md
Labels: documentation

#5 Create noeud.py
  noeud.py
Labels: enhancement
